- name: copy good test files
  copy:
    src: "{{ role_path }}/files/good_samples/"
    dest: "{{ mysql_backup_dir }}"
    owner: root
    group: root
    mode: 0644
  when: "{{ test_mode }} == true"
  
- name: copy bad test files
  copy:
    src: "{{ role_path }}/files/bad_samples/"
    dest: "{{ mysql_backup_dir }}"
    owner: root
    group: root
    mode: 0644
  when: "{{ test_mode }} == true and {{ test_false }} == true"  
  
- name: create shell script
  become: yes
  template:
    src: verify-checksum.j2
    dest: /tmp/verify-checksum.sh
    mode: 0777
    
- name: verify checksum
  become: yes
  shell: /tmp/verify-checksum.sh  